
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author engmagdymoheb
 */
public class AddAccountMenu extends javax.swing.JDialog {

    private Bank bank;
    private Customer customer;
    /**
     * Creates new form AddAccountMenu
     */
    public AddAccountMenu(java.awt.Frame parent, boolean modal,Bank bank) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.bank=bank;
        customer=null;
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        ssnLabel = new javax.swing.JLabel();
        ssnField = new javax.swing.JTextField();
        initialDepositLabel = new javax.swing.JLabel();
        initialDepositField = new javax.swing.JTextField();
        accountTypeLabel = new javax.swing.JLabel();
        accountTypeComboBox = new javax.swing.JComboBox<>();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add account menu");
        getContentPane().setLayout(new java.awt.GridLayout(6, 2, 5, 5));

        firstNameLabel.setText("First Name :");
        getContentPane().add(firstNameLabel);

        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(firstNameField);

        lastNameLabel.setText("Last Name :");
        getContentPane().add(lastNameLabel);
        getContentPane().add(lastNameField);

        ssnLabel.setText("Social Security Number :");
        getContentPane().add(ssnLabel);
        getContentPane().add(ssnField);

        initialDepositLabel.setText("Initial Deposit :");
        getContentPane().add(initialDepositLabel);
        getContentPane().add(initialDepositField);

        accountTypeLabel.setText("Account Type :");
        getContentPane().add(accountTypeLabel);

        accountTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Checking", "Savings" }));
        accountTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountTypeComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(accountTypeComboBox);

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountTypeComboBoxActionPerformed

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        StringBuilder warnings =new StringBuilder();
        String firstName="",lastName="",ssn="",depositString="";
        double amount =0;
        
        //verify first name field
        if(firstNameField.getText().isEmpty()){
            warnings.append("First Name mustn't be empty !\n");
            
        }else{
            firstName=firstNameField.getText();
        }
        
        //verify last name field
        if(lastNameField.getText().isEmpty()){
            warnings.append("Last Name mustn't be empty ! \n");
        }else{
            lastName=lastNameField.getText();
        }
        
        //verify ssn
  
        if(!ssnField.getText().matches("(\\d{3}-?){2}\\d{4}")){
            warnings.append("Social Security Number Incorrect Format ,xxx-xxx-xxxx !\n");
            
        }else{
            ssn=ssnField.getText().replace("-", "");
        }
        //verify deposit
        if(initialDepositField.getText().isEmpty()){
            warnings.append("Initial deposit must entered !");
        }else{
            try {
                amount = Bank.round(Double.parseDouble(initialDepositField.getText()), 2);
            } catch (NumberFormatException e) {
                warnings.append("Initial deposit must be a number ");
            }
        }
        if(warnings.length()>0){
            JOptionPane.showMessageDialog(this, warnings,"Input warning",JOptionPane.WARNING_MESSAGE);
        }else{
            AccountType accountType=AccountType.Undefined;
            Account account=null;
            if(accountTypeComboBox.getSelectedItem().toString() == "Checking"){
                if(amount>=100){
                    accountType=AccountType.Checking;
                    
                }else{
                    warnings.append("Initial deposit must be at least 100$ for Checking account");
                }
                
                
            }else if (accountTypeComboBox.getSelectedItem().toString() == "Savings"){
                if(amount>=50){
                    accountType=AccountType.Savings;
                }else{
                    warnings.append("Initial deposit must be at least 50$ for Savings account");
                }
                
            }
            if(accountType != AccountType.Undefined){
                
                customer=bank.openAccount(firstName, lastName, ssn, accountType, amount);
                
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, warnings.toString(), "Input Warnings", JOptionPane.WARNING_MESSAGE);
            }
            
        
        }
        
        //create an account
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> accountTypeComboBox;
    private javax.swing.JLabel accountTypeLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField initialDepositField;
    private javax.swing.JLabel initialDepositLabel;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField ssnField;
    private javax.swing.JLabel ssnLabel;
    // End of variables declaration//GEN-END:variables

    Customer getCustomer() {
        return customer;
    }
}

